### ISSUE TITLE
System.IndexOutOfRangeException: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by mariopossamato** [JiXiaomai/SMM2LevelViewer#12]
This exception occasionally occurs for me while scrolling through a level using a zoom greater than 16:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at SMM2VIEWER.Form2.P_MouseMove(Object sender, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by imkzh** [comment]
Change `MapA` to `MapB` at [Form1.vb:3750](https://github.com/JiXiaomai/SMM2LevelViewer/blame/a6ac4d24ba683fa02c166b36f64bbcfc24a033a5/Form1.vb#L3750) in sub `MapB_MouseMove(sender, e)` should solve the issue.

The code is checking current pointer location against wrong Map object.
