### ISSUE TITLE
EndOfStreamException Error when attempting to load a level that hasn't been downloaded yet.

### ISSUE THREAD

**Issue by VoltageMiner** [JiXiaomai/SMM2LevelViewer#9]
OS: Windows 10 x64
How to reproduce:
1) Delete SQG9NT9GF and SQG9NT9GF.DAT from MAP folder.
2) Open SMM2VIEWER v1.0.exe
3) Click Load Level Button
4) Exception occurs at L06 or beyond from observation.
The downloaded SQG9NT9GF.DAT is about 128KB when it should be around 376KB.

```
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at Microsoft.VisualBasic.FileSystem.FileGet(Int32 FileNumber, Byte& Value, Int64 RecordNumber)
   at SMM2VIEWER.ModuleSMM.LoadLvlData(String P, Boolean IO)
   at SMM2VIEWER.Form1.LoadEFile(Boolean IO)
   at SMM2VIEWER.Form1.RefPic()
   at SMM2VIEWER.Form1.Button5_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

**Comment by unsightedmetal6** [comment]
I am experiencing the same error. It used to work before, but now it doesn't.

**Comment by VoltageMiner** [comment]
> I am experiencing the same error. It used to work before, but now it doesn't.

Now it works. It might have been an issue with website.
